title: What the Efon
author:
  name: Efon
  email: whattheefon@gmail.com
description: > # this means to ignore newlines until "show_excerpts:" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.
  What the Efon ağgünce sayfası
show_excerpts: true # set to true to show excerpts on the homepage

language: tr
minima:
  date_format: "%-d %b %Y"

  # generate social links in footer
  social_links:
    - { platform: github,         user_url: "https://github.com/whattheefon" }
    - { platform: twitter,       user_url: "https://www.twitter.com/__efon__" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

permalink: /:title/

rss: rss

kramdown:
  input: GFM
  syntax_highlighter: rouge
    

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      tags: genel
  - scope:
      path: ''
      type: post_tags
    values:
      permalink: "/tags/:name/"
      layout: tag

collections:
  post_tags:
    permalink: /tags/:name/
    output: true
